### ISSUE TITLE
Update .deb to support building packages with submodules

### ISSUE THREAD

**Issue by marksvc** [flatpak/ppa-flatpak-builder#1]
The .deb package does not yet include [Allow use file protocol when update submodule.](https://github.com/flatpak/flatpak-builder/commit/b539ac812a32366725fb92fc440a0bbe3e46cffd) from https://github.com/flatpak/flatpak-builder. I look forward to this being included :-D

**Comment by smcv** [comment]
This change was part of flatpak-builder 1.2.3, which is available for Ubuntu 20.04 and up.

It is not currently available for Ubuntu 18.04 or 16.04. These older suites are unlikely to be kept fully up-to-date (especially with flatpak-builder) unless an Ubuntu developer volunteers to take over maintenance of the PPA.
